# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-02 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_card_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
