# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-02 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='outcome',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='outcome_type',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='seller_message',
        ),
    ]
