# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20240402_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
