# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_charge_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='payment_method',
            field=models.TextField(default='card'),
        ),
    ]
