# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2024-04-02 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20240402_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='payment_method',
        ),
    ]
